# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core gui network widgets x11extras
TEMPLATE = app
TARGET = OpsTrace
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -lX11 -lXss
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(OpsTrace.pri)
win32:RC_FILE = OpsTrace.rc

